server:
  port: 8189
  servlet:
    context-path: /conference
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:conference_bd;MODE=MySQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  flyway:
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: WA.test.conf.smtp@gmail.com
    password: veqveq123
    protocol: smtp
    properties:
      "mail.transport.protocol": smtp
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true